### ISSUE TITLE
Command terminated with exit code 139: -: line 6:   405 Segmentation fault      pgbackrest stanza-create --stanza="${stanza}" db          0s          Warning   UnableToCreateStanzas          postgrescluster/n8n                                  command terminated with exit code 139: -: line 6:   473 Segmentation fault      pgbackrest stanza-create --stanza="${stanza}" db          0s          Warning   UnableToCreateStanzas          postgrescluster/n8n                                  command terminated with exit code 139: -: line 6:   535 Segmentation fault      pgbackrest stanza-create --stanza="${stanza}"

### ISSUE THREAD

**Issue by haf** [pgbackrest/pgbackrest#1536]
1. pgBackRest version:

```yaml
  - name: RELATED_IMAGE_POSTGRES_13
    value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0"
  - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
    value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos8-13.4-3.1-0"
  - name: RELATED_IMAGE_PGBACKREST
    value: "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2"
  - name: RELATED_IMAGE_PGBOUNCER
    value: "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-2"
  - name: RELATED_IMAGE_PGEXPORTER
    value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.2-0"
```

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

GKE CoS stable channel

4. Did you install pgBackRest from source or from a package?

See above

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

When starting postgres-operator on GKE CoS with the above versions, you get segmentation faults!

```
db          0s          Warning   UnableToCreateStanzas          postgrescluster/n8n                                  command terminated with exit code 139: -: line 6:   635 Segmentation fault      pgbackrest stanza-create --stanza="${stanza}"
```
