### ISSUE TITLE
Patroni Bootstrapping replica - create_replica_methods.pgbackrest

### ISSUE THREAD

**Issue by bhairavdhanwade** [pgbackrest/pgbackrest#1613]
- pgBackRest version:2.36
- PostgreSQL version: 12
- Operating system/version -  Ubuntu 20.04
- Did you install pgBackRest from source or from a package? - package 

 Describe the issue:
 
1. We are trying to bootstrap replication node from leader by using PgBackrest.

2. PgBackrest working like charm restoring Backup as well WAL. After restoration when we check replica node status its shows you are behind master and i am not going to promote to accept connection and its goes panic mode.

3. We understand it's normal behaviour. Because while restoring data on node. Lot of data got generated on master node so new node is not on exact recovery_target_timeline. 

```
postgresql:
    create_replica_methods:
           - pgbackrest
    pgbackrest:
           command: "pgbackrest --stanza=test --delta restore --log-level-console=detail"
           keep_data: True
           no_params: True            
    recovery_conf:
        restore_command: "/usr/bin/pgbackrest --stanza=test archive-get %f %p"
        recovery_target_timeline: 'latest'         
```
We are observing that this node join patroni cluster but not able to sync with Leader.
Thanks, 
Bhairav
