### ISSUE TITLE
Question about recoverable timestamp ranges

### ISSUE THREAD

**Issue by shinyaaa** [pgbackrest/pgbackrest#1830]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.38

2. PostgreSQL version: 14.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Kubernetes 1.20

4. Did you install pgBackRest from source or from a package?
I use pgBackRest, which is bundled with PGO.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
PITR can be implemented in PGO by applying the following yaml file. But we do not know which time ranges can be specified . Is there any way to know this? Or do we need to check manually with a method like pg_waldump?
```
spec:
  dataSource:
    postgresCluster:
      clusterName: hippo
      repoName: repo1
      options:
      - --type=time
      - --target="2021-06-09 14:15:11-04"
```
https://access.crunchydata.com/documentation/postgres-operator/5.1.2/tutorial/disaster-recovery/

Regards,
Shinya Kato
