### ISSUE TITLE
Standby Leader failed to join cluster

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#2239]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.48

2. PostgreSQL version: 14.x

3. Operating system/version - Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? From Source.

5. Describe the issue: 

**Case1:** We are creating Standby Leader but by mistake `archive_coomand`  and `restore_command` flag were also enabled on Standby Leader. So backup restoration is failed **with below error which is expected behaviour** because it ended up archiving that *.history timeline.
`FATAL,XX000,"requested timeline 32 is not a child of this server's history","Latest checkpoint is at 94C/92BF1218 on timeline 30, but in the history of the requested timeline, the server forked off from that timeline at 94B/602A5FE8`

**Case 2:** But after this we disabled the  `archive_mode`  and `archive_command` flag on Standby Leader node and took new full backup from master node and we are using `replica_method=pgbackrest` on Standby Leader node. So we are expecting that restoration should be complete this time but it failed with same error again.

Below is some config part of `patroni.yml` file on Standby Leader:

```
bootstrap:
      dcs:
         postgresql:
            method: pgbackrest
            pgbackrest:
              command: "/etc/boot_pgbackrest.sh"
              keep_existing_recovery_conf: false
              keep_data: false
              no_params: false

        standby_cluster:
           host: 10.13.25.3 # Primary Leader or haproxy
           port: 5432
           primary_slot_name: system_streaming  #replica physical slot
           restore_command: "/usr/bin/pgbackrest --stanza=system archive-get %f %p"   

           create_replica_methods:
             - pgbackrest
             - basebackup
           pgbackrest:
             command: "pgbackrest --stanza=system --log-level-console=detail --delta --target-action=promote --type=immediate restore --link-all"
             keep_existing_recovery_conf: false
             keep_data: false
             no_params: false
```

**Case3 :** But when we create a new stanza with different `repo1-path` and took the new full backup and used same `repo1-path` on Stanby Leader than it successfully promote Standby Leader.

Now **Case 1** and **Case 3** are clear to me but I am expecting it should work with **Case 2** as well.

Can you please help me why it does not work in Case 2?

Thank You

**Comment by Tekchanddagar** [comment]
Hello Team,
Can you please help me to understand the **case 2**?

Thank You

**Comment by pgstef** [comment]
Hi,

> We are creating Standby Leader but by mistake archive_coomand and restore_command flag were also enabled on Standby Leader.

What do you call a _standby leader_? you mean that server has been a primary for some time and push WAL archives to your repo?

> But when we create a new stanza with different repo1-path and took the new full backup and used same repo1-path on Stanby Leader than it successfully promote Standby Leader.

It is still not clear to me what you're trying to achieve. What's the link between taking a backup and a successful promote?
I mean to build your standby replica, you need a successful PG recovery first. As soon as your replica is up and connected to your primary, yes, you can promote it (by i.e. performing a switch-over).

> Can you please help me to understand the case 2?

You need to clean-up the repository. If you take a new backup of timeline X (your primary) but have mistakenly pushed timeline X+1 from another primary, PG will try to follow the latest generated timeline in the repo (X+1) but it won't work since it wasn't generated from the same cluster. That's why starting with a fresh repo worked (case 3).

Usually when running the restore manually, you could ask to follow the "current" timeline (see recovery_target_timeline PG setting) to stay on your backup timeline. But after the recovery, you might want to switch back to "latest" for the streaming replication before promoting the standby. That's why simply removing the wrong timeline generated in your repo might be way easier thing to do.

If your "good" primary is on timeline 30 (decimal, meaning 0000001E in hexadecimal), everything after that (wal archives and history files) might be moved out from your repo if you want to clean-up the things generated by mistake...

Kind Regards,

**Comment by Tekchanddagar** [comment]
@pgstef , First of all Thank You for your answer.
> What do you call a _standby leader_?

We are creating a Standby cluster and there is no relation between Standby cluster and Primary Cluster. And Standby Cluster has Standby Leader node. Please refer the below URL for more info:

[Standby Cluster](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html)


> It is still not clear to me what you're trying to achieve.

We are trying to create Standby cluster.

Below is the part of `patroni.yml` config on Standby Cluster node:

```
bootstrap:
      dcs:
         postgresql:
            method: pgbackrest
            pgbackrest:
              command: "/etc/boot_pgbackrest.sh"
              keep_existing_recovery_conf: false
              keep_data: false
              no_params: false

        standby_cluster:
           host: 10.13.25.3 # Primary Leader or haproxy
           port: 5432
           primary_slot_name: system_streaming  #replica physical slot
           restore_command: "/usr/bin/pgbackrest --stanza=system archive-get %f %p"   

           create_replica_methods:
             - pgbackrest
             - basebackup
           pgbackrest:
             command: "pgbackrest --stanza=system --log-level-console=detail --delta --target-action=promote --type=immediate restore --link-all"
             keep_existing_recovery_conf: false
             keep_data: false
             no_params: false
```
In the above config you can we are using method pgbackrest for replication and when we start bootstrap it will restore the backup from S3 bucket and later replication will start from Primary cluster.

Now we kept `archive_mode` and `archive_command` enable on Standby Cluster node so when postgres service start it push the wal in repo and `wal_replay` failed which is expected.

But as I said in **Case 2** we took the new full backup from Primary Cluster and again tried bootstrap Stanby Cluster and we are expecting it will use the new full backup (Becuase pgbackrest use latest backup to restore if we didn't specify any particular backup). So we are expecting it should be success now but it failed again.

So I am not sure why its happening and want to know what mistake I am doing here.

Can you please help me?

Thank You
