### ISSUE TITLE
Backup takes too long - how to reduce backup time?

### ISSUE THREAD

**Issue by robertpba** [pgbackrest/pgbackrest#2248]
We have observed that pgBackRest backups are slow.

Here some relevant info:
1. pgBackRest version: 2.47-1
2. PostgreSQL version: 15.4-3.3-1
3. Operating system/version: company-internal Kubernetes cluster running on Linux.
4. pgBackRest install: from crunchydata image.

The backups section of our PostgresCluster deployment:

```yaml
  backups:
    pgbackrest:
      global:
        buffer-size: 1MiB
        compress-level: '1'
        compress-level-network: '1'
        compress-type: gz
        process-max: '6'
        repo1-retention-full: '2'
        repo1-retention-full-type: count
        start-fast: 'y'
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-1
      jobs:
        ttlSecondsAfterFinished: 86400
      repoHost:
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
      repos:
      - name: repo1
        schedules:
          incremental: "0 4 * * 1-6"
          full: "0 4 * * 0"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 100Gi
      sidecars:
        pgbackrest:
          resources:
            limits:
              cpu: 4
              memory: 1Gi
            requests:
              cpu: 4
              memory: 1Gi
```

We did some tests on a small proof-of-concept installation with 50 GB of data in the database. The fastest we could do the 50 GB backup, with `compress-level: '1'`, was 04:59 (mm:ss), with a backup size of 18.5 GB.

We arrived at this as the fastest backup time after tuning the `compress-level` parameter. With `compress-level: '9'` it took 19:03 (mm:ss), producing a backup size of 17.5 GB, and with `compress-level: '6'` (the default for gzip) it took 09:13 (mm:ss), also producing a backup size of 17.5 GB. So setting `compress-level` to 1 is a good compromise of only slightly larger backup size but significantly faster backup. We also experimented with several other settings, such as `cpu`, `memory`, `buffer-size`, `process-max`, and found the current settings to be the best.

However, we are doing these tests in preparation for the migration of a larger database to Crunchy Postgres: currently 12 TB, growing at 3 TB a year, the system to run for at least another 5 years, which by then should have 27 TB of data.

Assuming a linear increase of backup times, the above settings would require 19:56 (hh:mm) to backup 12 TB of data, and 44:51 (hh:mm) for 27 TB of data. Given that we plan to make weekly full backups (on Sundays) and daily incremental backups, these times are way too long. As a maximum we could accept 12, perhaps even 18 hours on a Sunday, but no more.

Is there any way to realistically achieve this? I should add that we don't have unlimited CPU and memory resources, as we pay for our Kubernetes namespace per CPU.
