### ISSUE TITLE
PITR doesn't work wuth patroni 

### ISSUE THREAD

**Issue by lbouquinD** [pgbackrest/pgbackrest#2323]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.5
2. PostgreSQL version:
15.1
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?
From source 
5. Please attach the following as applicable:
pgbackrest.conf: 
```
[main]
pg1-path=/data/appli/patroni/data
pg1-port=5434
pg1-host=192.168.0.2
pg1-user=root
pg2-path=/data/appli/patroni/data
pg2-port=5434
pg2-host=192.168.0.3
pg2-user=root

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-host-user=postgres
start-fast=y
```
```
scope: se-patroni-test-1
namespace: /service/  # valeur par défaut
name: postgres1
restapi:
  listen:  postgres1.mydomain.com:5432
  connect_address: postgres1.mydomain.com:5432

  certfile: /data/appli/certs/postgres1.mydomain.com.crt
  keyfile:  /data/appli/certs/postgres1.mydomain.com.key
  cafile: /data/appli/certs/ca.crt

log:
  level: INFO
  dir: /data/appli/patroni/logs/se-patroni-test-1
etcd:
  hosts: ['postgres1.mydomain.com:2379', 'postgres2.mydomain.com:2379']

  cacert: /data/appli/certs/ca.crt
  cert: /data/appli/certs/postgres1.mydomain.com.crt
  key: /data/appli/certs/postgres1.mydomain.com.key


  protocol: https

bootstrap:
  method: pgbackrest
  pgbackrest:
      command: /var/lib/pgsql/custom_bootstrap.sh
      keep_existing_recovery_conf: False
      no_params: False
      recovery_conf:
          recovery_target: immediate
          recovery_target_action: pause
          restore_command: pgbackrest --stanza=main archive-get %f %p
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: logical
        hot_standby: on
        max_wal_senders: 100
        max_replication_slots: 50
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host all all all md5
    - hostssl all all all md5
    - host replication replicator all md5
    - hostssl replication replicator all md5
  users:
    dba:
      password: dba_password
      options:
      - createrole
      - createdb
postgresql:
  listen: "*:5434"
  connect_address: postgres1.mydomain.com:5434
  data_dir: /data/appli/patroni/data
  bin_dir: /usr/pgsql-15/bin/
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: root
      password: password
    rewind:
      username: rewind
      password: password
  parameters:
    unix_socket_directories: '.'
    wal_keep_size: 10000
    wal_level: logical

    ssl: off
    ssl_key_file:  /data/appli/certs/postgres1.mydomain.com.key
    ssl_cert_file: /data/appli/certs/postgres1.mydomain.com.crt
    ssl_ca_file: /data/appli/certs/ca.crt

    archive_command : 'pgbackrest --stanza=main archive-push %p'
    archive_mode : 'on'
    archive_timeout : 60
    #restore_command : 'pgbackrest --log-level-console=detail --stanza=main  --set=20240409-083304F_20240409-101152I  restore'
    #restore_command : 'pgbackrest --staniza=main archive-get %f "%p"'

    log_destination: 'stderr'
    logging_collector: 'on'
    log_directory: '/data/appli/patroni/logs'
    log_filename: 'postgresql-%Y-%m-%d.log'
    log_statement: 'all'

  basebackup:
    max-rate: "100M"
    checkpoint: "fast"
watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false


```

curtom_bootstrap.sh:  
```
#!/bin/sh

mkdir -p /data/appli/patroni/data
pgbackrest --stanza=main  --log-level-console=info --delta --type=time "--target=2024-04-11 12:45:04.915768+02" --target-action=promote  restore
```

7. Describe the issue:
I want to  use PITR  to restauration: 

I created table with date in insert  and set  a cron to insert data  each minute. 
In controlleur pgbacklrest  I set  a full  backup  and set  a cron to incremental  backup  each  hour. 

When I restore with  PITR I have an issue. 
The restauration get  the befor hour but not in time that I want. Before restauration I delete all  data and i see that all data is set

--target=2024-04-11 12:45:04.915768+02 
In this example restore the increment to  12h01:00  work  but not reload wal between 12h01  and 12:45.  Why ?  ( The mlast data is 12 ans not 12h45 )
