### ISSUE TITLE
meson: how-to `make install`?

### ISSUE THREAD

**Issue by k0ste** [pgbackrest/pgbackrest#2332]
Hi, I try to switch version 2.51 to meson build, after `NOTE TO PACKAGERS`

My current commands is:

```shell
meson setup --buildtype "release" "pgbackrest" "pgbackrest-release-2.51"
ninja -vC "pgbackrest"
meson install -C "pgbackrest" --destdir="/tmp/here"
```

The build complete flawless, on install subcommand meson tells me:

```
ninja: Entering directory `/srv/raid/filez/sandbox/AUR/pgbackrest/src/pgbackrest'
[2/2] Generating src/command/help/help.auto.c.inc with a custom command
Nothing to install.
```

**Comment by pgstef** [comment]
Hi,

Have you looked into the [user-guide](https://pgbackrest.org/user-guide.html#build)?
The user-guide doesn't really use the install step, it just uses a simple copy from `/build/pgbackrest/src/pgbackrest` to `/usr/bin`. Which is also what was done in the old make [section](https://pgbackrest.org/user-guide-rhel.html#build). And which is also what the [rpm pgdg](https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob_plain;f=rpm/redhat/main/common/pgbackrest/main/pgbackrest.spec;hb=HEAD) package is doing.

What's your OS btw?

I recently updated my Ansible playbook to use meson too:

```yml
- set_fact:
    pkg_config_path: "PKG_CONFIG_PATH=/usr/pgsql-{{ pg_version }}/lib/pkgconfig"
  when: ansible_os_family == 'RedHat'

- name: Configure pgbackrest
  shell: "{{ pkg_config_path | default('', true) }} meson setup {{ pgbackrest_build_dir }} {{ pgbackrest_src_dir }} --prefix={{ pgbackrest_build_prefix }} --bindir={{ pgbackrest_build_prefix }}/bin"

- name: Build pgbackrest
  shell: "ninja -C {{ pgbackrest_build_dir }}"

- name: Install pgbackrest
  shell: "ninja install"
  args:
    chdir: "{{ pgbackrest_build_dir }}"
```

which pretty much would give on rhel systems:

```bash
export PKG_CONFIG_PATH=/usr/pgsql-16/lib/pkgconfig 
meson setup $pgbackrest_build_dir $pgbackrest_src_dir --prefix=/usr --bindir=/usr/bin
cd $pgbackrest_build_dir
ninja
su
ninja install
```

**Comment by k0ste** [comment]
```
- name: Install pgbackrest
  shell: "ninja install"
  args:
    chdir: "{{ pgbackrest_build_dir }}"
```

This command will produce this output

```
[1/3] /srv/raid/filez/sandbox/AUR/pgbackrest/src/pgbackrest/src/build-code postgres ../pgbackrest-release-2.51/src/postgres/../..
[2/3] /srv/raid/filez/sandbox/AUR/pgbackrest/src/pgbackrest/src/build-code help ../pgbackrest-release-2.51/src/command/help/../../..
[2/3] /usr/bin/meson install --no-rebuild
Nothing to install.
```
