### ISSUE TITLE
Cannot reinit a standby after failover without making a full or incremental backup

### ISSUE THREAD

**Issue by mmartinello** [pgbackrest/pgbackrest#2474]
I am testing **pgBackRest** on top a **PostgreSQL cluster managed by Patroni** using a dedicated **pgBackRest repository host** with a **S3 (MinIO) repository type**.

I configured `archive_command`, `restore_command` and `create_replica_methods` to use pgBackRest on PostgreSQL/Patroni nodes.

**Full and incremental backups work good from the repository host**, and I don't see errors on archiving commands from PostgreSQL nodes.

Reinit of nodes works good when the PostgreSQL timeline do not change, but if a failover happens and the timeline change the standby node **is no more able to rejoin the cluster using pgBackRest** and I see multiple errors like this:

```
patroni-1  | 2024-10-24 16:14:20.320 UTC [2471] LOG:  started streaming WAL from primary at 1A0/28000000 on timeline 68
patroni-1  | 2024-10-24 16:14:20.315 P00   INFO: unable to find 00000044000001A000000028 in the archive
patroni-1  | 2024-10-24 16:14:20.331 P00   INFO: unable to find 00000047.history in the archive
```

In the example above, the cluster moved to timeline, but **the standby cluster remains on the timeline 68**.

Whenever **I do a new full or incremental backup from the repository host**, the standby nodes are able to join the cluster immediately with the new timeline 70.

What I want to understand if this behaviour is expected: a failover can happen anytime, and what I understand is that the backup chain break when a new timeline is created, isn't it?

If it's true, would it be a best practice to trigger an automatic full backup when a new timeline is created due to a failover?

Do you have any hint about this?

---

**1. pgBackRest version:** pgBackRest 2.53.1

**2. PostgreSQL version:** PostgreSQL 12

**3. Operating system/version:** Debian 11 Bullseye

4. Did you install pgBackRest from source or from a package? From APT packages

**`pgbackrest.conf` file on PostgreSQL node:**

```
[global]

repo1-type=s3
repo1-path=/repo
repo1-s3-endpoint=pgbackrest-minio
repo1-s3-bucket=pgbackrest-dev
repo1-s3-uri-style=path
repo1-s3-verify-tls=n
repo1-s3-key=<my_key>
repo1-s3-key-secret=<my_secret>
repo1-s3-region=<my_minio_region>
repo1-cipher-pass=<my_pass>
repo1-cipher-type=aes-256-cbc

repo1-retention-full=14
repo1-retention-full-type=time
repo1-host-user=postgres

archive-check=n
process-max=2
log-level-console=info
log-path=/var/log/pgbackrest
log-level-file=debug
start-fast=y
delta=y

[dev]
pg1-local=y
pg1-path=/var/lib/postgresql/data
```

**`pgbackrest.conf` file on pgBackRest repository host:**

```
[global]
#repo1-path=/data/backup/dev/pgbackrest

repo1-retention-full=14
repo1-retention-full-type=time
repo1-host-user=postgres
repo1-type=s3
repo1-path=/repo
repo1-s3-endpoint=pgbackrest-minio
repo1-s3-bucket=pgbackrest-dev
repo1-s3-uri-style=path
repo1-s3-verify-tls=n
repo1-s3-key=<my_key>
repo1-s3-key-secret=<my_secret>
repo1-s3-region=<my_minio_region>
repo1-cipher-pass=<my_pass>
repo1-cipher-type=aes-256-cbc

archive-check=n
process-max=2
log-level-console=info
log-path=/var/log/pgbackrest
log-level-file=debug
start-fast=y
delta=y

[dev]
pg1-host=postgres1
pg1-host-user=postgres
pg1-host-port=8022
pg1-database=postgres
pg1-path=/var/lib/postgresql/data/
pg1-port=5432

pg2-host=postgres2
pg2-host-user=postgres
pg2-host-port=8022
pg2-database=postgres
pg2-path=/var/lib/postgresql/data/
pg2-port=5432

pg3-host=postgres3
pg3-host-user=postgres
pg3-host-port=8022
pg3-database=postgres
pg3-path=/var/lib/postgresql/data/
pg3-port=5432
```

**`postgresql.conf` settings applicable to pgBackRest:**
 (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`):

```
[...]
bootstrap:
  dcs:
    postgresql:
      use_pg_rewind: true
      parameters:
        archive_command: "pgbackrest --stanza=dev archive-push %p"
        archive_mode: "on"
        restore_command: "pgbackrest --stanza=dev archive-get %f \"%p\""
      recovery_conf:
        recovery_target_timeline: latest
        restore_command: pgbackrest --stanza=dev archive-get %f "%p"

  method: pgbackrest
  pgbackrest:
    command: pgbackrest --stanza=dev restore
    keep_existing_recovery_conf: False
    recovery_conf:
      recovery_target_timeline: latest
      restore_command: pgbackrest --stanza=dev archive-get %f "%p"

postgresql:
  create_replica_methods:
    - pgbackrest
  pgbackrest:
    command: pgbackrest --stanza=dev restore --delta --link-all
    keep_data: True
    no_params: True

  parameters:
    archive_command: "pgbackrest --stanza=dev archive-push %p"
    archive_mode: "on"
    restore_command: "pgbackrest --stanza=dev archive-get %f \"%p\""
```

**errors in the postgresql log file before or during the time you experienced the issue:**

```
patroni-1  | 2024-10-24 16:14:15.312 UTC [2442] LOG:  started streaming WAL from primary at 1A0/28000000 on timeline 68
patroni-1  | 2024-10-24 16:14:15.312 UTC [2442] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000045000001A000000028 has already been removed
patroni-1  | P00   WARN: environment contains invalid option 'ssh-run'
patroni-1  | P00   WARN: environment contains invalid option 'host-repo-dir-path'
patroni-1  | P00   WARN: environment contains invalid option 'ssh-host-port'
patroni-1  | P00   WARN: environment contains invalid option 'host-log-dir-path'
patroni-1  | 2024-10-24 16:14:15.317 P00   INFO: archive-get command begin 2.53.1: [00000047.history, pg_wal/RECOVERYHISTORY] --exec-id=2444-287a8477 --log-level-console=info --log-level-file=debug --log-path=/var/log/pgbackrest --pg1-local --pg1-path=/var/lib/postgresql/data --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/repo --repo1-s3-bucket=pgbackrest-dev --repo1-s3-endpoint=pgbackrest-minio --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=<my_minio_region> --repo1-s3-uri-style=path --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=dev
patroni-1  | 2024-10-24 16:14:15.321 P00   INFO: unable to find 00000047.history in the archive
patroni-1  | 2024-10-24 16:14:15.321 P00   INFO: archive-get command end: completed successfully (5ms)
patroni-1  | P00   WARN: environment contains invalid option 'ssh-run'
patroni-1  | P00   WARN: environment contains invalid option 'host-repo-dir-path'
patroni-1  | P00   WARN: environment contains invalid option 'ssh-host-port'
patroni-1  | P00   WARN: environment contains invalid option 'host-log-dir-path'
patroni-1  | 2024-10-24 16:14:20.290 P00   INFO: archive-get command begin 2.53.1: [00000046000001A000000028, pg_wal/RECOVERYXLOG] --exec-id=2466-ace0eef4 --log-level-console=info --log-level-file=debug --log-path=/var/log/pgbackrest --pg1-local --pg1-path=/var/lib/postgresql/data --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/repo --repo1-s3-bucket=pgbackrest-dev --repo1-s3-endpoint=pgbackrest-minio --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=<my_minio_region> --repo1-s3-uri-style=path --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=dev
patroni-1  | 2024-10-24 16:14:20.295 P00   INFO: unable to find 00000046000001A000000028 in the archive
patroni-1  | 2024-10-24 16:14:20.295 P00   INFO: archive-get command end: completed successfully (6ms)
```
