### ISSUE TITLE
cert owner - root or postgres? pgbackrest cant decide what he wants

### ISSUE THREAD

**Issue by germebl** [pgbackrest/pgbackrest#2498]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
`pgBackRest 2.53.1`

2. PostgreSQL version:
`PostgreSQL 17.0 - Percona Server for PostgreSQL 17.0.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
```
debian-12 backup server: 
pgbackrest 10.1.201.16

debian-12 patroni/etcd cluster: 
pgsql-1 10.1.202.5
pgsql-2 10.1.202.6
pgsql-3 10.1.202.7
```

4. Did you install pgBackRest from source or from a package?
`Percona Package Repository`

5. Please attach the following as applicable:
pgbackrest.conf on backup server:
```
[global] 

# Server repo details
repo1-path=/var/lib/pgbackrest 

### Retention ###
#  - repo1-retention-archive-type
#  - If set to full pgBackRest will keep archive logs for the number of full backups defined by repo-retention-archive
repo1-retention-archive-type=full 

# repo1-retention-archive
#  - Number of backups worth of continuous WAL to retain
#  - NOTE: WAL segments required to make a backup consistent are always retained until the backup is expired regardless of how this option is configured
#  - If this value is not set and repo-retention-full-type is count (default), then the archive to expire will default to the repo-retention-full
# repo1-retention-archive=2 

# repo1-retention-full
#  - Full backup retention count/time.
#  - When a full backup expires, all differential and incremental backups associated with the full backup will also expire. 
#  - When the option is not defined a warning will be issued. 
#  - If indefinite retention is desired then set the option to the max value. 
repo1-retention-full=4 

# Server general options
process-max=12
log-level-console=info
#log-level-file=debug
log-level-file=debug
start-fast=y
delta=y
backup-standby=y 

########## Server TLS options ##########
tls-server-address=*
tls-server-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt
tls-server-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key
tls-server-ca-file=/etc/ssl/certs/pg_ha/ca.crt 

### Auth entry ###
tls-server-auth=pgsql-1=cluster_1
tls-server-auth=pgsql-2=cluster_1
tls-server-auth=pgsql-3=cluster_1 

### Clusters and nodes ###
[cluster_1]
pg1-host=pgsql-1
pg1-host-port=8432
pg1-port=5432
pg1-path=/var/lib/postgresql/17/main
pg1-host-type=tls
pg1-host-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt
pg1-host-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key
pg1-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt
pg1-socket-path=/var/run/postgresql 

pg2-host=pgsql-2
pg2-host-port=8432
pg2-port=5432
pg2-path=/var/lib/postgresql/17/main
pg2-host-type=tls
pg2-host-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt
pg2-host-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key
pg2-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt
pg2-socket-path=/var/run/postgresql 

pg3-host=pgsql-3
pg3-host-port=8432
pg3-port=5432
pg3-path=/var/lib/postgresql/17/main
pg3-host-type=tls
pg3-host-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt
pg3-host-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key
pg3-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt
pg3-socket-path=/var/run/postgresql
```

pgbackrest.conf on patroni node 1:
```
[global]
repo1-host=pgbackrest
repo1-host-user=postgres
repo1-host-type=tls
repo1-host-cert-file=/etc/ssl/certs/pg_ha/pgsql-1.crt
repo1-host-key-file=/etc/ssl/certs/pg_ha/pgsql-1.key
repo1-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt

# general options
process-max=16
log-level-console=info
log-level-file=debug

# tls server options
tls-server-auth=pgbackrest=cluster_1
tls-server-address=*
tls-server-cert-file=/etc/ssl/certs/pg_ha/pgsql-1.crt
tls-server-key-file=/etc/ssl/certs/pg_ha/pgsql-1.key
tls-server-ca-file=/etc/ssl/certs/pg_ha/ca.crt

[cluster_1]
pg1-path=/var/lib/postgresql/17/main
```

pgbackrest.conf on patroni node 2:
```
[global]
repo1-host=pgbackrest
repo1-host-user=postgres
repo1-host-type=tls
repo1-host-cert-file=/etc/ssl/certs/pg_ha/pgsql-2.crt
repo1-host-key-file=/etc/ssl/certs/pg_ha/pgsql-2.key
repo1-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt

# general options
process-max=16
log-level-console=info
log-level-file=debug

# tls server options
tls-server-address=*
tls-server-cert-file=/etc/ssl/certs/pg_ha/pgsql-2.crt
tls-server-key-file=/etc/ssl/certs/pg_ha/pgsql-2.key
tls-server-ca-file=/etc/ssl/certs/pg_ha/ca.crt
tls-server-auth=pgbackrest=cluster_1

[cluster_1]
pg1-path=/var/lib/postgresql/17/main
```

pgbackrest.conf on patroni node 3:
```
[global]
repo1-host=pgbackrest
repo1-host-user=postgres
repo1-host-type=tls
repo1-host-cert-file=/etc/ssl/certs/pg_ha/pgsql-3.crt
repo1-host-key-file=/etc/ssl/certs/pg_ha/pgsql-3.key
repo1-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt

# general options
process-max=16
log-level-console=info
log-level-file=debug

# tls server options
tls-server-address=*
tls-server-cert-file=/etc/ssl/certs/pg_ha/pgsql-3.crt
tls-server-key-file=/etc/ssl/certs/pg_ha/pgsql-3.key
tls-server-ca-file=/etc/ssl/certs/pg_ha/ca.crt
tls-server-auth=pgbackrest=cluster_1

[cluster_1]
pg1-path=/var/lib/postgresql/17/main

```

patroni.yaml:
```
namespace: percona_lab
scope: cluster_1
name: pgsql-1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.1.202.5:8008

etcd3:
    host: 10.1.202.5:2379

bootstrap:
  post_bootstrap: /opt/post_bootstrap.sh
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
      ttl: 30
      loop_wait: 10
      retry_timeout: 10
      maximum_lag_on_failover: 1048576

      postgresql:
          use_pg_rewind: true
          use_slots: true
          parameters:
              wal_level: replica
              hot_standby: on
              wal_keep_segments: 10
              max_wal_senders: 5
              max_replication_slots: 10
              wal_log_hints: on
              logging_collector: 'on'
              max_wal_size: '10GB'
              archive_mode: on
              archive_timeout: 600s
              archive_command: pgbackrest --stanza=cluster_1 archive-push /var/lib/postgresql/17/main/pg_wal/%f
          recovery_conf:
            restore_command: pgbackrest --stanza=main archive-get %f %p

  # some desired options for 'initdb'
  initdb: # Note: It needs to be a list (some options need values, others are switches)
      - encoding: UTF8
      - data-checksums

  pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
      - host replication replicator 127.0.0.1/32 trust
      - host replication replicator 0.0.0.0/0 md5
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5

postgresql:
    cluster_name: cluster_1
    listen: 0.0.0.0:5432
    connect_address: 10.1.202.5:5432
    data_dir: /var/lib/postgresql/17/main
    bin_dir: /usr/lib/postgresql/17/bin
    pgpass: /tmp/pgpass0
    authentication:
        replication:
            username: replicator
            password: 'supersecret'
        superuser:
            username: postgres
            password: anothersupersecret
    parameters:
        unix_socket_directories: /var/run/postgresql/
    create_replica_methods:
        - basebackup
    basebackup:
        checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```

7. Describe the issue:

When trying to create a stanza i'm getting the error:
```
2024-11-26 14:47:23.693 P00   WARN: unable to check pg3: [FileReadError] key file '/etc/ssl/certs/pg_ha/pgbackrest.key' must be owned by the 'root' user or root
2024-11-26 14:47:23.693 P00  DEBUG:     command/exit::exitSafe: (result: 0, error: true, signalType: 0)
2024-11-26 14:47:23.693 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
                                    HINT: are all available clusters in recovery?
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:
                                    
                                    version: 2.53.1
                                    command: stanza-create
                                    options: --exec-id=1314-74d9c88a --log-level-console=info --log-level-file=debug --pg1-host=pgsql-1 --pg2-host=pgsql-2 --pg3-host=pgsql-3 --pg1-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt --pg2-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt --pg3-host-ca-file=/etc/ssl/certs/pg_ha/ca.crt --pg1-host-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt --pg2-host-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt --pg3-host-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt --pg1-host-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key --pg2-host-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key --pg3-host-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key --pg1-host-port=8432 --pg2-host-port=8432 --pg3-host-port=8432 --pg1-host-type=tls --pg2-host-type=tls --pg3-host-type=tls --pg1-path=/var/lib/postgresql/17/main --pg2-path=/var/lib/postgresql/17/main --pg3-path=/var/lib/postgresql/17/main --pg1-port=5432 --pg2-port=5432 --pg3-port=5432 --pg1-socket-path=/var/run/postgresql --pg2-socket-path=/var/run/postgresql --pg3-socket-path=/var/run/postgresql --repo1-path=/var/lib/pgbackrest --stanza=cluster_1
                                    
                                    stack trace:
                                    db/helper.c:dbGet:132:(primaryOnly: false, primaryRequired: true, standbyRequired: false)
                                    command/stanza/create.c:cmdStanzaCreate:(void)
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
```

If i change it as requested to `root:root`:

```
chown root:root /etc/ssl/certs/pg_ha/pgbackrest.key
```

The following error appears when trying to restart pgbackrest:

```
2024-11-26 15:09:27.328 P00  ERROR: [095]: unable to load key file '/etc/ssl/certs/pg_ha/pgbackrest.key': [2147483661] no details available
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:
                                    
                                    version: 2.53.1
                                    command: server
                                    options: --exec-id=1397-bf869d90 --log-level-console=info --log-level-file=debug --tls-server-address=* --tls-server-auth=pgsql-1=cluster_1 --tls-server-auth=pgsql-2=cluster_1 --tls-server-auth=pgsql-3=cluster_1 --tls-server-ca-file=/etc/ssl/certs/pg_ha/ca.crt --tls-server-cert-file=/etc/ssl/certs/pg_ha/pgbackrest.crt --tls-server-key-file=/etc/ssl/certs/pg_ha/pgbackrest.key
                                    
                                    stack trace:
                                    common/crypto/common.c:cryptoErrorCode:45:(test build required for parameters)
                                        ... function(s) omitted ...
                                    common/io/tls/server.c:tlsServerNew:(host: {"*"}, caFile: {"/etc/ssl/certs/pg_ha/ca.crt"}, keyFile: {"/etc/ssl/certs/pg_ha/pgbackrest.key"}, certFile: {"/etc/ssl/certs/pg_ha/pgbackrest.crt"}, timeout: 1860000)
                                    command/server/server.c:cmdServer:(argListSize: 2, argList: (char *[]))
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
```

I've checked on the backup server and on the patroni nodes the ca.crt and verified with openssl the certificates - it reports OK. When trying to do a connection via openssl:
```
openssl s_client -connect 10.1.202.5:8432 -CAfile ca.crt -cert pgbackrest.crt -key pgbackrest.key
```

The connection builds up and validates the TLS certificates - so they seem to be fine. At the end it throws me the same error as seen above.

Just cause i found another issue with a issue which is mostly the same i want to say, that i actually solving the dns via the /etc/hosts cause our dns isnt actually that stable. I would change that when we will setup again for production.

So the 3 patroni nodes having the pgbackrest.domain.lan with the short hostname pgbackrest on the correct ip in their /etc/hosts. The backup server for pgbackrest has the 3 patroni nodes with there hostname and the short version + himself.

So when trying to resolve via `host` the hostnames like `pgsql-1` they resolve correct to the ip of the node.

//Edit
As it is installed as package, the systemd service file was delivered by the package:
```
[Unit]
Description=pgBackRest Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=postgres
Group=postgres
ExecStart=/usr/bin/pgbackrest server
ExecStartPost=/bin/sleep 3
ExecStartPost=/bin/bash -c "[ ! -z $MAINPID ]"
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

So the service is running with the postgres user - so i dont understand why pgbackrest want to have the cert key owned by root.
