### ISSUE TITLE
Error during setup Standby Cluster

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#2509]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.51

2. PostgreSQL version: 16.x

3. Operating system/version - Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? APT

5. Describe the issue: We are creating DR site and trying to setup Standby Cluster on DR site. But when we are trying to create Standby Leader on DR site we are getting below error:

```
2024-12-20 06:59:09.111 UTC,,,224877,,676515bc.36e6d,7,,2024-12-20 06:59:08 UTC,,0,FATAL,XX000,"requested timeline 3 is not a child of this server's history","Latest checkpoint is at 0/DEAD on timeline 2, but in the history of the requested timeline, the server forked off from that timeline at F94/CE43D7E8.",,,,,,,,"","startup",,0
```
AFAIK we get this error if some `wal` is pushed on repository from DR DB node. But I can confirm `archive_mode` and `archive_command` are disabled on DR node. 

**So we have tried below approach ae well:**

We take new full backup from Primary DB and then tried again to create Standby Cluster (`archive_mode=off`). But still we are getting same error. But we are expecting it should work with new full backup.

Below is the config part in my `patroni.yml` file on Standby Cluster side:

```
namespace: /dbs/
name: SF-DR-APPLE-DB-002

restapi:
  listen: 10.13.134.121:8008
  connect_address: 10.13.134.121:8008

etcd:
  hosts: 10.13.134.104:2379
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
              archive_mode: off
              archive_command: ''
              unix_socket_directories: '/var/run/postgresql'
              wal_level: replica
              
            method: pgbackrest
            pgbackrest:
              command: "/etc/boot_pgbackrest.sh"
              keep_existing_recovery_conf: false
              keep_data: false
              no_params: false

        standby_cluster:
           host: 10.13.242.232 # Primary Leader or haproxy
           port: 5436
           primary_slot_name: apple_db_streaming  #replica physical slot
           restore_command: "/usr/bin/pgbackrest --stanza=apple archive-get %f %p"   

           create_replica_methods:
             - pgbackrest
             #- basebackup
           pgbackrest:
             command: "pgbackrest --stanza=apple --log-level-console=debug --delta --target-action=promote --type=immediate restore --link-all"
             keep_existing_recovery_conf: false
             recovery_target_timeline: latest 
             keep_data: false
             no_params: false

slots:
  apple_db_streaming:
    active: true
    type: physical             

```

Can you please help me to find out the answer why its not working even with new full backup. We can see it was using new full backup but failed during `wal_replay`

Thank You

**Comment by pgstef** [comment]
> Latest checkpoint is at 0/DEAD on timeline 2, but in the history of the requested timeline, the server forked off from that timeline at F94/CE43D7E8.

This error message indicates that something is wrong with your restore process. See the comments of the 0/DEAD in the [code](https://github.com/pgbackrest/pgbackrest/blob/main/src/postgres/interface.h#L90): _This will prevent PostgreSQL from starting if backup_label is not present_. The backup_label should be in the backup and not touched after the restore, since it is important for PG recovery.

If you messed up with the repository content somehow, obviously you should fix it, but using `--target-timeline=current` could potentially help PG recovery to stay on the timeline of the backup set (and if you took a fresh full backup from your primary, the backup timeline should be the timeline of your principal cluster too).

> command: "pgbackrest --stanza=apple --log-level-console=debug --delta --target-action=promote --type=immediate restore --link-all"

That command is imo not suitable for creating a replica. It would restore the backup and ask PG to perform recovery until the backup consistency point and then promote as a primary. AFAIK, in Patroni a standby cluster is still able to replicate from the main cluster, so the "standby leader" should stay a standby node able to connect in streaming replication to the main cluster (it's only cascading replication ultimately).

BTW, your problem might also come from the `keep_existing_recovery_conf: false` where Patroni would override the settings generated by pgBackRest for the recovery and you're not providing any recovery settings with Patroni itself.

You could first try without Patroni to restore the backup (i.e. using `--type=standby`, which would first try to replay all the WAL archives and then try to connect into streaming replication if proper primary_conninfo has been setup), as we can't really help you with Patroni config.

The only thing I can tell about Patroni is that I usually use these settings for create replica:

```yml
create_replica_methods:
    - pgbackrest
    - basebackup
  pgbackrest:
    command: pgbackrest restore --stanza=apple --delta --type=preserve
    keep_data: True
    no_params: True
  basebackup:
    checkpoint: 'fast'
```

And for the bootstrap section, to create a new cluster from a backup rather than initdb, I often use:

```yml
method: pgbackrest
pgbackrest:
  command: pgbackrest restore --stanza=prod-db-cluster
  keep_existing_recovery_conf: False
  no_params: True
  recovery_conf:
    recovery_target_action: promote
    recovery_target_timeline: latest
    restore_command: pgbackrest --stanza=prod-db-cluster archive-get %f %p
```

But it depends on the pgBackRest configuration and repository content obviously (which is something you didn't provided). Unless you're doing manual operations with pgBackRest and provide configs/logs of what's not working, we might not be able to help you further.
